# Generated by Django 5.0.1 on 2024-01-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('run_time', models.PositiveIntegerField()),
                ('director', models.CharField(max_length=200)),
                ('actors', models.CharField(max_length=200)),
                ('year', models.PositiveIntegerField()),
            ],
        ),
    ]
